# Generated by Django 6.0.4 on 2026-04-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_order_store_rename_name_product_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
